[package]
name = "tpt-for-symbolic-exec"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Whole-program symbolic execution."

readme = "README.md"
keywords = ["symbolic-execution", "verification", "smt", "static-analysis", "testing"]
categories = ["science", "development-tools::testing", "algorithms"]

[dependencies]
tpt-for-smt-lite = { workspace = true }

[lints]
workspace = true
