[package]
name = "tpt-for-abstract-interp"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Generic abstract-interpretation framework."

readme = "README.md"
keywords = ["abstract-interpretation", "static-analysis", "verification", "semantics", "analysis"]
categories = ["science", "mathematics", "development-tools::debugging"]

[dependencies]

[lints]
workspace = true

[[example]]
name = "abstract_interp_basic"
path = "examples/interval_analysis.rs"

