[package]
name = "tpt-for-trace-macros"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Trace / instrumentation macros for verification (no_std global tracer)."

[dependencies]

[features]
default = ["std"]
std = []
alloc = []

[lints]
workspace = true
