[package]
name = "tpt-for-vcgen"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Verification-condition generation."

readme = "README.md"
keywords = ["vcgen", "verification", "formal-verification", "logic", "proof"]
categories = ["science", "mathematics", "rust-patterns"]

[dependencies]
tpt-for-smt-lite = { workspace = true }

[lints]
workspace = true
